FROM node:20

# Create app directory
WORKDIR /home/openbackhaul/administratorAdministration

# Install and app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

#RUN npm install
RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 3028

#Command to start the application
CMD [ "node", "index.js" ]
