@startuml is001_regardApplication
skinparam responseMessageBelowArrow true

title
is-001_regardApplication
end title

participant "RO" as ro
participant "AA://v1/regard-application" as aa

ro -> aa : {newApplicationName, releaseNumber, protocol, address, port} (apiKey)
activate aa

  note over aa
  RegardApplicationCausesSequenceForInquiringBasicAuthRequestApprovals
  end note

  note left aa
  IF (client-successfully-added==true)
  end note
  aa --> ro : { successfully-connected==true}

deactivate aa

note over aa
IF (NOT 200) OR (client-successfully-added==false)
end note

aa --\ aa 

activate aa

  note over aa
  RegardApplicationCausesSequenceForInquiringOamRequestApprovals
  end note

  note left aa
  IF (client-successfully-added==true)
  end note
  aa --> ro : { successfully-connected==true}

  note over aa
  IF (NOT 200) OR (client-successfully-added==false)
  end note

  aa --> ro : { successfully-connected==false, reason-of-failure}

deactivate aa

@enduml