@startuml is004_approveOamRequest
skinparam responseMessageBelowArrow true

title
is004_approveOamRequest
end title

participant "ApplicationPattern" as ap
participant "AA://v1/approve-basic-auth-request" as aa

ap -> aa : {applicationName, releaseNumber, authorization, method} (apiKey)
activate aa

aa --> ap : {oam-request-is-approved, reason-of-objection}

deactivate aa

@enduml